### PR TITLE
Require pm^4.7

### PR DESCRIPTION
**Pull request by AIPTU**

### CODE REVIEW

**Comment by Swift-Strider** [comment]
Hello, and thank you for leaving my project a PR. I see that you're requiring a more recent version of pocketmine, could you explain how this benefits my library or plugin authors who use this library?

**Comment by AIPTU** [comment]
I think this library is quite useful to developers because it provides sounds that have not been implemented by pm itself.

**Comment by Swift-Strider** [comment]
Thank you, its nice hearing that my project is helpful. But why should it target pm `^4.7` instead of `4.0.0`? Are you having issues with `composer require`-ing this project? Does this fix an issue?

**Comment by AIPTU** [comment]
Yeah
`diamondstrider1/sounds 1.2.0 requires pocketmine/pocketmine-mp 4.0.0 -> found pocketmine/pocketmine-mp[4.0.0] but it conflicts with your root composer.json require (^4.7).`

**Comment by Swift-Strider** [comment]
Oops, I intended for the version to be `^4.0` which would fix your problem. Would you mind changing your PR to target version `^4.0` instead, so the library isn't restrained to 4.7 and up? Once you do I think the PR will be ready to merge and I will realease a new version.

**Comment by AIPTU** [comment]
Done

**Comment by Swift-Strider** [comment]
Thank you, expect Sounds v1.2.1 soon!

**Comment by Swift-Strider** [comment]
I made a slight hiccup, but now Sounds `v1.2.2` instead of `v1.2.1` should work for your project! 😄

**Pull request merged**
